### Minimum Edit Distance

Below you can find a function for calculating the Minimum Edit Distance between two strings. Unfortunately, the implementation is missing one crucial part, the one that fills in the table.

Can you fill it in by yourself?

In [1]:
import numpy as np

In [6]:
ops=['i','d','s']

def MED (src_str,trg_str):
    src_str = "#"+src_str
    trg_str = "#"+trg_str
    
    ins_cost = 1
    del_cost = 1
    sub_cost = 2
    
    m = len(src_str)
    n = len(trg_str)
    
    #INITIALIZE DISTANCE MATRIX WITH ZEROS
    distance_matrix = np.zeros((n,m))

    #INITIALIZE COLUMN 0 VALUES
    distance_matrix [:,0] = np.arange(0,n,del_cost)
    #INITIALIZE ROW 0 VALUES
    distance_matrix [0,:] = np.arange(0,m,ins_cost)    
    
    #Fill in the table
    for i in range(1, n):
        for j in range(1, m):
            #insertion
            insertion = distance_matrix[i, j - 1] + ins_cost
            deletion = distance_matrix[i - 1, j] + del_cost
            if src_str[j] == trg_str[i]:
                substitution = distance_matrix[i - 1, j -1 ]
            else:
                substitution = distance_matrix[i - 1, j - 1] + sub_cost
            distance_matrix[i,j] = min([insertion, deletion, substitution])
            
    #If you uncomment the following command you can see
    #the distance matrix in the same way
    #that appears in Figure 3.27 from the SLP2 book, page 111.
    print (np.flip(distance_matrix.T, axis=0))
    
    #RETURN THE LAST ELEMENT
    return distance_matrix[-1,-1]

MED ("HOUSE","PROSE")

[[5. 6. 7. 6. 5. 4.]
 [4. 5. 6. 5. 4. 5.]
 [3. 4. 5. 4. 5. 6.]
 [2. 3. 4. 3. 4. 5.]
 [1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5.]]


4.0