In [1]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
import gensim
from gensim.models import KeyedVectors

# Load vectors directly from the file
# YOU HAVE TO CHANGE THE PATH
model = KeyedVectors.load_word2vec_format('./wiki.en.vec.short50K', binary=False)

Let's work on the geometric properties of word embeddings. What happens if we remove the content of *man* related to the word *king* and if we add the content of *woman*?

If we want to do this, first we need to perform subtraction and addition over vectorial representations of the words:

In [4]:
#The vectorial representation of the word queen (first 5 numbers)
model['queen'][:5]

array([-0.060511,  0.049607, -0.20885 ,  0.10349 ,  0.14276 ],
      dtype=float32)

In [5]:
#The vectorial representation of the word woman (first 5 numbers)
model['woman'][:5]

array([ 0.25962 ,  0.17535 , -0.12542 , -0.080696, -0.061302],
      dtype=float32)

In [6]:
#The vectorial representation of the word man (first 5 numbers)
model['man'][:5]

array([-0.011586, -0.076437, -0.2499  ,  0.028163, -0.35323 ],
      dtype=float32)

Can you please calculate the resulting vector of removing the "woman" content and adding the "man" content? Then, you can save it in a variable.

In [7]:
#YOUR CODE HERE
vec = model.get_vector('queen') - model.get_vector('woman') + model.get_vector('man')

Now you can use the function *model.similar_by_vector*, which does the same as the *model.most_similar* function, but instead of providing a word, we can provide a vector.

Then, use the *model.similar_by_vector* function, and let's see what are the most similar words to that vector.

In [8]:
#YOUR CODE HERE
model.similar_by_vector(vec)

[('queen', 0.7898672223091125),
 ('king', 0.6429405808448792),
 ('majesty', 0.5372264385223389),
 ('monarch', 0.5126069784164429),
 ('crown', 0.4697607159614563),
 ('queens', 0.4569217562675476),
 ('whitehall', 0.45084935426712036),
 ('reign', 0.4498361051082611),
 ('coronation', 0.44729694724082947),
 ('royal', 0.43049025535583496)]

Now, can you find more examples of that kind? Maybe not only with gender, but with cultures, geography, music, and so on

In [8]:
#YOUR CODE HERE
